### ISSUE TITLE
Need to click twice after Cancel button or popout used

### ISSUE THREAD

**Issue by timo002** [tavicu/bs-confirmation#15] opened 2015-06-22 15:30 UTC
When I click on the Cancel button, or click outside the confirmation dialog. I need to click twice on the link again to activate tho confirmation dialog again.

When I toggle the confirmation dialog by clicking on the button while the dialog is open. I can reopen it again by just clicking once.

Using bootstrap 3.5.5
Issue persists on different browsers (latest versions) and devices.

**Comment by rodrigoporcionato** [comment] 2015-07-12 05:33
Me too. Any solution?

**Comment by tavicu** [comment] 2015-07-12 17:20
I will try to reproduce the bug this week and see what i can do.

**Comment by Rafeethu** [comment] 2015-07-12 17:48
having the same bug. i just debugged in the console. i have noticed that the data inState->click on bs.confirmation is not set to false when the confirmation is closed by clicking no btn or clicking outside. when we click again then the inState->click is set to false. 

when we click the button second time. it's showing the confirmation and setting the inState->click to true.

can this be the cause? i cannot explore further..

![image](https://cloud.githubusercontent.com/assets/1304358/8639071/42bed6d6-28ec-11e5-97b8-17ab744f1ab3.png)

**Comment by Rafeethu** [comment] 2015-07-13 07:19
in the onHide event, if we set 

`var dt = $(element).data();
dt['bs.confirmation']['inState']['click'] = false;`

then it's working without this issue.

**Comment by tavicu** [comment] 2015-07-14 08:16
It was a bug only with Bootstrap 3.3.5. They added the inState method and since the confirmation works with click and call the hide method on click cancel it didn't change the click state to false.

I've updated it and it works now.

I will also work this weekend on a new and cleaner version :)

Thanks for your help.

**Closed by tavicu** 2015-07-14 08:16 UTC
Labels: bug
