### ISSUE TITLE
The plugin does not work in Asp.Net WebForms

### ISSUE THREAD

**Issue by edwardmeng** [tavicu/bs-confirmation#41] opened 2016-03-31 09:59 UTC
The server side  post back events of Asp.Net WebForms are based on the name of the buttons. So we cannot just submit the nearest form to instead of the button click event in the WebForms.

**Comment by tavicu** [comment] 2017-12-22 13:19
Duplicate of https://github.com/tavicu/bs-confirmation/issues/47

**Closed by tavicu** 2017-12-22 13:19 UTC
